---
- hosts: testing
  gather_facts: false
  become: true

  tasks:

  - name: "list dir"
    ansible.builtin.shell: ls
    register: result

  - name: Print shell output
    ansible.builtin.debug:
      var: result
  
  - name: Apt update
    ansible.builtin.apt:
      update_cache: true
  
  - name: Install a requirements
    ansible.builtin.apt:
      pkg:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - software-properties-common 
      - mc
  
  - name: Install docker gpg key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  - name: Add docker repository
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Apt update
    ansible.builtin.apt:
      update_cache: true
